export const Majors = [
  { value: "Accounting" },
  { value: "Aerospace Engineering" },
  { value: "Agribusiness" },
  { value: "Agricultural Communications & Journalism" },
  { value: "Agricultural Economics" },
  { value: "Agricultural Leadership & Development" },
  { value: "Agricultural Science" },
  { value: "Agricultural Systems Management" },
  { value: "Animal Science" },
  { value: "Anthropology" },
  { value: "Applied Mathematics" },
  { value: "Architectural Engineering" },
  { value: "Architecture" },
  { value: "Biochemistry" },
  { value: "Bioenvironmental Sciences" },
  { value: "Biological & Agricultural Engineering" },
  { value: "Biology" },
  { value: "Biomedical Engineering" },
  { value: "Biomedical Sciences" },
  { value: "Business Administration" },
  { value: "Business Honors" },
  { value: "Chemical Engineering" },
  { value: "Chemistry" },
  { value: "Civil Engineering" },
  { value: "Classics" },
  { value: "Coastal Environmental Science & Society" },
  { value: "Communication" },
  { value: "Community Health" },
  { value: "Computer Engineering" },
  { value: "Computer Science" },
  { value: "Computing" },
  { value: "Construction Science" },
  { value: "Dance Science" },
  { value: "Data Engineering" },
  { value: "Ecology & Conservation Biology" },
  { value: "Economics" },
  { value: "Education - Bilingual Education" },
  {
    value:
      "Education - Language Arts/Social Studies Middle Grades Certification",
  },
  { value: "Education - Math/Science Middle Grades Certification" },
  { value: "Education - PreK-6 Generalist Certification" },
  { value: "Education - Special Education" },
  { value: "Electrical Engineering" },
  { value: "Electronic Systems Engineering Technology" },
  { value: "English" },
  { value: "Entomology" },
  { value: "Environmental Engineering" },
  { value: "Environmental Geosciences" },
  { value: "Environmental Studies" },
  { value: "Finance" },
  { value: "Financial Planning" },
  { value: "Food Science & Technology" },
  { value: "Forensic & Investigative Sciences" },
  { value: "General Studies" },
  { value: "Genetics" },
  { value: "Geographic Information Science & Technology" },
  { value: "Geography" },
  { value: "Geology" },
  { value: "Geophysics" },
  { value: "Health" },
  { value: "History" },
  { value: "Horticulture" },
  { value: "Hospitality, Hotel Management, & Tourism" },
  { value: "Human Resource Development" },
  { value: "Industrial & Systems Engineering" },
  { value: "Industrial Distribution" },
  { value: "Information Technology Service Management" },
  { value: "Interdisciplinary Engineering" },
  { value: "International Affairs" },
  { value: "International Studies" },
  { value: "International Studies (Politics & Diplomacy Track)" },
  { value: "Journalism" },
  { value: "Kinesiology - Dance Science" },
  { value: "Kinesiology - Exercise & Sport Science" },
  { value: "Kinesiology - Exercise Science" },
  { value: "Landscape Architecture" },
  { value: "Management" },
  { value: "Management Information Systems" },
  { value: "Manufacturing & Mechanical Engineering Technology" },
  { value: "Marine Biology" },
  { value: "Marine Engineering Technology" },
  { value: "Marine Fisheries" },
  { value: "Marine Sciences" },
  { value: "Marine Transportation" },
  { value: "Maritime Business Administration" },
  { value: "Maritime Studies" },
  { value: "Marketing" },
  { value: "Materials Science & Engineering" },
  { value: "Mathematics" },
  { value: "Mechanical Engineering" },
  { value: "Meteorology" },
  { value: "Microbiology" },
  { value: "Modern Languages (French, German, or Russian)" },
  { value: "Molecular and Cell Biology" },
  { value: "Multidisciplinary Engineering Technology" },
  { value: "Neuroscience - Behavioral and Cognitive Track" },
  { value: "Neuroscience - Molecular and Cellular Track" },
  { value: "Nuclear Engineering" },
  { value: "Nursing" },
  { value: "Nutrition" },
  { value: "Ocean Engineering" },
  { value: "Ocean Studies" },
  { value: "Oceanography" },
  { value: "Performance & Visual Studies" },
  { value: "Petroleum Engineering" },
  { value: "Philosophy" },
  { value: "Physics" },
  { value: "Plant & Environmental Soil Science" },
  { value: "Political Science" },
  { value: "Poultry Science" },
  { value: "Psychology" },
  { value: "Public Health" },
  { value: "Rangeland, Wildlife, & Fisheries Management" },
  { value: "Recreation Park & Tourism Sciences" },
  { value: "Sociology" },
  { value: "Spanish" },
  { value: "Sport Management" },
  { value: "Statistics" },
  { value: "Supply Chain Management" },
  { value: "Technology Management" },
  { value: "Telecommunication Media Studies" },
  { value: "Turfgrass Science" },
  { value: "University Studies - Arts and Sciences" },
  { value: "University Studies - Business" },
  {
    value: "University Studies - Global Arts, Planning, Design & Construction",
  },
  { value: "University Studies - Leadership Studies" },
  { value: "University Studies - Marine Environmental Law & Policy" },
  { value: "University Studies - Mathematics for Secondary Teaching" },
  { value: "University Studies - Oceans & One Health" },
  { value: "University Studies - Race, Gender, & Ethnicity" },
  { value: "University Studies - Society, Ethics, & Law" },
  { value: "University Studies - Tourism & Coastal Community Development" },
  { value: "Urban & Regional Planning" },
  { value: "Visualization" },
  { value: "Wildlife & Fisheries Sciences" },
  { value: "Women's & Gender Studies" },
  { value: "Zoology" },
  { value: "Other" },
];
