name: Rails tests
on: [push, pull_request]
env:
  RUBY_VERSION: 3.1.2
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  DATABASE_USER: postgres
  DATABASE_PASSWORD: password
  DATABASE_HOST: localhost
  FRONTEND_ORIGIN: localhost:3000
  AUTH_SECRET: "7OxgCPqJVDFlFQTrlJQg49JNIS/vKxQaBdIZCZ2MJ8U="
  NEXT_PUBLIC_AUTHJS_LOCAL_SESSION_COOKIE: "next-auth.session-token"
  NEXT_PUBLIC_AUTHJS_SESSION_COOKIE: "next-auth.session-token"
  NEXTAUTH_URL: http://localhost:3001
  NEXT_PUBLIC_API_URL: http://localhost:3000
  NEXT_PUBLIC_NEXTAUTH_URL: http://localhost:3001

jobs:
  rspec-test:
    name: Automated Testing
    # Pin to a stable, supported Ubuntu 22.04 image
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install postgres client
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Install dependencies
        run: |
          cd backend
          gem install bundler
          bundle install

      - name: Create database
        run: |
          cd backend
          bundle exec rails db:create db:migrate RAILS_ENV=test

      - name: Install Yarn dependencies
        run: |
          cd backend
          yarn install

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Run Jest tests
        run: |
          cd frontend
          npm test

      - name: Run RSpec tests
        run: |
          cd backend
          bundle exec rspec

      - name: Run Brakeman
        run: |
          cd backend
          brakeman -o brakeman.txt

      - name: Run RuboCop
        run: |
          cd backend
          bundle exec rubocop --force-exclusion --out rubocop.txt

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: backend/coverage

      - name: Upload RuboCop report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: rubocop-report.txt
          path: backend/rubocop.txt

      - name: Upload Brakeman report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: brakeman-report.txt
          path: backend/brakeman.txt
